---
# tasks file for ansible-role-consul

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- name: Include user and group setup
  import_tasks: user_group_setup.yml

- name: Include directory settings
  import_tasks: dirs_setup.yml

- name: Install OS packages and consul - locally
  include_tasks: install.yml
